### PR TITLE
Alexis work please merge it

### PR DESCRIPTION
**Pull request by akalexiskelly**
work 1 done

### CODE REVIEW

**Comment by mucahitekin** [comment]
awesome :)

**Comment by MKayaSdet** [comment]
hgfvyjhb

**Review by MKayaSdet — APPROVED** [review]

**Review by MKayaSdet — CHANGES_REQUESTED** [review]
addd more codes

**Review by mucahitekin — CHANGES_REQUESTED** [review]
in the print statement, you should usee "" instead " "

**Pull request merged**
